### ISSUE TITLE
не работает (Linux Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by Myxa228** [nordbearbotdev/Torpeda#12]
когда я вписываю номер, то он пишет что спам отправляется однако ничего не происходит, проверял на своем

**Comment by nordbearbotdev** [comment]
> когда я вписываю номер, то он пишет что спам отправляется однако ничего не происходит, проверял на своем

В данный момент в бомбере мало сервисов. Поэтому приходит/или вообще не приходят смс
