### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by N9sha18** [nordbearbotdev/Torpeda#7]
Traceback (most recent call last):
  File "/storage/emulated/0/Download/Termux/torpeda/main.py", line 24, in <module>
    from termcolor import colored
ModuleNotFoundError: No module named 'termcolor'

**Comment by nordbearbotdev** [comment]
Hmm...

**Comment by nordbearbotdev** [comment]
One moment

**Comment by nordbearbotdev** [comment]
You need to install the missing modules yourself. This is not a mistake

**Comment by N9sha18** [comment]
> You need to install the missing modules yourself. This is not a mistake

I installed everything from requirements.txt what's Missing?

**Comment by nordbearbotdev** [comment]
> > You need to install the missing modules yourself. This is not a mistake
> 
> You should have added termcolor in requirements.txt

What OS you use?

**Comment by N9sha18** [comment]
> > > You need to install the missing modules yourself. This is not a mistake
> > 
> > 
> > You should have added termcolor in requirements.txt
> 
> What OS you use?

I am using this on termux

**Comment by N9sha18** [comment]
> > > > You need to install the missing modules yourself. This is not a mistake
> > > 
> > > 
> > > You should have added termcolor in requirements.txt
> > 
> > 
> > What OS you use?
> 
> I am using this on termux

And this only works with Russian mobile numbers?

**Comment by nordbearbotdev** [comment]
> > > > > You need to install the missing modules yourself. This is not a mistake
> > > > 
> > > > 
> > > > You should have added termcolor in requirements.txt
> > > 
> > > 
> > > What OS you use?
> > 
> > 
> > I am using this on termux
> 
> And this only works with Russian mobile numbers?
I'm sorry, but so far, yes. If you want it to work for your country, you can help.

**Comment by N9sha18** [comment]
> > > > > > You need to install the missing modules yourself. This is not a mistake
> > > > > 
> > > > > 
> > > > > You should have added termcolor in requirements.txt
> > > > 
> > > > 
> > > > What OS you use?
> > > 
> > > 
> > > I am using this on termux
> > 
> > 
> > And this only works with Russian mobile numbers?
> 
> I'm sorry, but so far, yes. If you want it to work for your country, you can help.

Yea I would love to help I am from india, so for this to work in my country you need api list right?

**Comment by nordbearbotdev** [comment]
> 
of course. We will create a special file where you will make this list

**Comment by nordbearbotdev** [comment]
> > > > > > > You need to install the missing modules yourself. This is not a mistake
> > > > > > 
> > > > > > 
> > > > > > You should have added termcolor in requirements.txt
> > > > > 
> > > > > 
> > > > > What OS you use?
> > > > 
> > > > 
> > > > I am using this on termux
> > > 
> > > 
> > > And this only works with Russian mobile numbers?
> > 
> > 
> > I'm sorry, but so far, yes. If you want it to work for your country, you can help.
> 
> Yea I would love to help I am from india, so for this to work in my country you need api list right?


https://github.com/nordbearbotdev/Torpeda/wiki - This English Wiki of torpeda! Write this. please)))
